"""AI Cover Letter Generator schemas.

Generated by AWS Bedrock (see `app.service.ai_service.AIService`, the same
Bedrock integration `AIProfileWriterService` / `AITextAssistService` /
`JobMatchService` already use) from the logged-in candidate's own profile
+ latest resume detail, tailored to one specific job posting (`job_id`).

Kept as its own module -- mirroring `app/schema/ai_profile_writer.py` and
`app/schema/ai_text_assist.py` -- rather than bolted onto
`app/job_application_schema.py`, since this is AI-generated draft content
the candidate reviews/edits before it is ever attached to an application
(via the existing `cover_letter_text` field on
`POST /candidate/applications/with-resume`), not a persisted schema
itself.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, field_validator

MAX_ADDITIONAL_NOTES_LENGTH = 1000
MAX_EXISTING_TEXT_LENGTH = 6000


class AICoverLetterTone(str, Enum):
    """Tone the generated cover letter should be written in."""

    PROFESSIONAL = "professional"
    CONFIDENT = "confident"
    FRIENDLY = "friendly"
    CONCISE = "concise"
    ENTHUSIASTIC = "enthusiastic"


class AICoverLetterLength(str, Enum):
    """Target length for the generated cover letter."""

    SHORT = "short"
    MEDIUM = "medium"
    LONG = "long"


class AICoverLetterRequest(BaseModel):
    """Request body for `POST /candidate/cover-letter/generate`.

    `job_id` is required -- a cover letter is always tailored to one
    specific job posting (title, company, and requirements pulled server
    side, never trusted from the client). When `existing_text` is present
    the model revises that exact draft (e.g. after the candidate tweaked
    it, or to apply a new `tone`/`length`) instead of drafting from
    scratch, mirroring the transform-mode pattern already used by
    `AIProfileWriterService`.
    """

    job_id: str = Field(
        min_length=1,
        description="The job posting to tailor the cover letter to.",
    )
    tone: AICoverLetterTone | None = Field(
        default=None,
        description="Optional tone for the generated letter. Defaults to a neutral professional tone when omitted.",
    )
    length: AICoverLetterLength | None = Field(
        default=None,
        description="Optional target length. Defaults to 'medium'.",
    )
    additional_notes: str | None = Field(
        default=None,
        max_length=MAX_ADDITIONAL_NOTES_LENGTH,
        description=(
            "Optional free-text context from the candidate to weave in, "
            "e.g. 'Mention my open-source contributions' or 'I was "
            "referred by a current employee'. Never a source of new "
            "employment facts -- only used to steer emphasis/framing."
        ),
    )
    existing_text: str | None = Field(
        default=None,
        max_length=MAX_EXISTING_TEXT_LENGTH,
        description=(
            "The candidate's current, unsaved draft of the cover letter. "
            "When provided, the model revises this exact text (applying "
            "any new `tone`/`length`/`additional_notes`) instead of "
            "drafting a fresh letter."
        ),
    )

    @field_validator("job_id")
    @classmethod
    def _job_id_must_have_content(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("job_id must not be blank")
        return value


class AICoverLetterResponse(BaseModel):
    """AI Cover Letter Generator API response.

    `cover_letter_text` is ready to drop straight into the existing
    `cover_letter_text` field of
    `POST /candidate/applications/with-resume` (see
    `app/job_application_schema.py`) once the candidate reviews/edits it.
    `job_title` / `company_name` echo the job posting used (server-side
    facts, never AI output) so the frontend can confirm what the letter
    was tailored to without a second lookup.
    """

    cover_letter_text: str = Field(description="AI-generated cover letter, ready to review/edit.")
    job_id: str = Field(description="The job posting this letter was tailored to.")
    job_title: str = Field(description="The job's title, echoed from the job posting (not AI-generated).")
    company_name: str | None = Field(
        default=None,
        description="The hiring company's name, echoed from the job posting (not AI-generated).",
    )

    model_config = ConfigDict(from_attributes=True)