from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


# The five buckets interview questions are grouped into. "Coding" is only
# populated when the job actually calls for hands-on coding ability -- see
# `AIInterviewQuestionService._build_prompt` -- so a non-technical job can
# come back with zero "Coding" questions and its slots redistributed among
# the other four categories.
QUESTION_CATEGORIES = ("Technical", "Coding", "Project-based", "Behavioral", "HR")

MIN_QUESTIONS = 15
MAX_QUESTIONS = 20


class InterviewQuestionItem(BaseModel):
    """A single AI-generated, candidate-personalized interview question.

    `sample_answer` is a concise model answer grounded only in the
    candidate's own profile/resume data (never invented experience or
    skills) -- see `AIInterviewQuestionService._build_prompt` for the
    grounding rules enforced on the AI prompt.
    """

    id: int = Field(default=0, description="1-based position of this question in the set.")
    category: str = Field(description=f"One of: {', '.join(QUESTION_CATEGORIES)}.")
    question: str = Field(description="The interview question text.")
    sample_answer: str = Field(
        alias="sampleAnswer",
        description="A concise sample answer personalized to the candidate's background.",
    )

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)


class AIInterviewQuestionsResponse(BaseModel):
    """AI Interview Question Generator API response.

    Generated by AWS Bedrock (see `app.service.ai_service.AIService`) from
    the job's title, company, description, skills, responsibilities, and
    requirements combined with the logged-in candidate's profile and
    latest resume -- so questions and sample answers are personalized to
    both sides, unlike a purely job-grounded question set.
    """

    job_id: str = Field(description="Identifier of the job this question set was generated for.")
    job_title: str = Field(alias="jobTitle")
    company_name: str = Field(default="", alias="companyName")

    questions: List[InterviewQuestionItem] = Field(
        default_factory=list,
        description=f"{MIN_QUESTIONS}-{MAX_QUESTIONS} personalized interview questions.",
    )

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)
