"""AI Resume / Profile Writer schemas.

Generated by AWS Bedrock (see `app.service.ai_service.AIService`, the same
Bedrock integration used by `JobMatchService` / AI Job Match Score) from the
logged-in candidate's own profile + latest resume detail. This feature
rewrites the candidate's Professional Headline, Professional Summary /
About, and Experience bullet descriptions into stronger, ATS-friendly copy
without inventing new facts (see `AIProfileWriterService` for how
fabrication is prevented).

Kept as its own module -- mirroring `app/schema/job_match.py` -- rather than
bolted onto `app/schema/profile.py`, since this is AI-generated draft
content the candidate reviews/accepts, not a persisted profile schema.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class AIProfileWriterSection(str, Enum):
    """The individually-regenerable sections this feature supports."""

    HEADLINE = "headline"
    ABOUT = "about"
    EXPERIENCE = "experience"


ALL_SECTIONS: tuple[AIProfileWriterSection, ...] = (
    AIProfileWriterSection.HEADLINE,
    AIProfileWriterSection.ABOUT,
    AIProfileWriterSection.EXPERIENCE,
)


class AIProfileWriterTone(str, Enum):
    """Tone the generated/rewritten copy should be written in."""

    PROFESSIONAL = "professional"
    CONFIDENT = "confident"
    FRIENDLY = "friendly"
    CONCISE = "concise"
    ENTHUSIASTIC = "enthusiastic"


class AIProfileWriterLength(str, Enum):
    """Target length for the generated copy. Most meaningful for `about`
    (Headline is always kept to a single line regardless)."""

    SHORT = "short"
    MEDIUM = "medium"
    LONG = "long"


class AIProfileWriterMode(str, Enum):
    """What the AI should do with the section.

    `GENERATE` is used when the field is empty (or the candidate simply
    wants a fresh draft). The remaining modes only make sense when the
    field already has candidate-written text -- they ask the model to
    transform that specific text rather than draft new copy from the
    profile alone.
    """

    GENERATE = "generate"
    IMPROVE = "improve"
    REWRITE = "rewrite"
    MAKE_ATS_FRIENDLY = "make_ats_friendly"
    SHORTEN = "shorten"
    EXPAND = "expand"


class AIProfileWriterRequest(BaseModel):
    """Request body for the "generate all sections" endpoint.

    `target_role` is optional -- when omitted the service falls back to the
    candidate's own `target_roles` profile field, so callers never have to
    duplicate data the candidate already provided.
    """

    target_role: Optional[str] = Field(
        default=None,
        max_length=255,
        description=(
            "Optional role to tailor the generated content toward, e.g. "
            "'Senior Backend Engineer'. Defaults to the candidate's own "
            "target role(s) on file when omitted."
        ),
    )
    tone: Optional[AIProfileWriterTone] = Field(
        default=None,
        description="Optional tone for the generated copy. Defaults to a neutral professional tone when omitted.",
    )
    length: Optional[AIProfileWriterLength] = Field(
        default=None,
        description="Optional target length, mainly used for the 'about' section. Defaults to 'medium'.",
    )


class AIProfileWriterRegenerateRequest(AIProfileWriterRequest):
    """Request body for the "regenerate a single section" endpoint."""

    section: AIProfileWriterSection = Field(
        description="Which single section to regenerate: 'headline', 'about', or 'experience'.",
    )
    mode: AIProfileWriterMode = Field(
        default=AIProfileWriterMode.GENERATE,
        description=(
            "What to do with the section. Use 'generate' when the field is "
            "empty. When the candidate already has text in the field, use "
            "'improve', 'rewrite', 'make_ats_friendly', 'shorten', or "
            "'expand' to transform `existing_text` instead of drafting from "
            "scratch."
        ),
    )
    existing_text: Optional[str] = Field(
        default=None,
        max_length=4000,
        description=(
            "The candidate's current, unsaved draft text for this field (as "
            "typed in the UI right now). Required for every mode except "
            "'generate' -- the model transforms this exact text rather than "
            "the value already saved on the candidate's profile."
        ),
    )


class AIProfileExperienceEntry(BaseModel):
    """One rewritten experience entry.

    `title` and `company` always echo the candidate's own resume data --
    never AI output -- so the improved description can never be attached to
    a fabricated role or employer.
    """

    title: str = Field(description="The candidate's own job title for this role (not AI-generated).")
    company: str = Field(description="The candidate's own employer name for this role (not AI-generated).")
    description: str = Field(
        default="",
        description="AI-rewritten, ATS-friendly bullet-point description of this role.",
    )


class AIProfileWriterResponse(BaseModel):
    """AI Resume/Profile Writer API response.

    On the "generate all sections" endpoint every field is populated. On
    the "regenerate one section" endpoint only the requested field is
    populated; the others are omitted from the JSON body via
    `response_model_exclude_none=True` on the route.
    """

    headline: Optional[str] = Field(
        default=None,
        description="AI-improved Professional Headline.",
    )
    professional_summary: Optional[str] = Field(
        default=None,
        description="AI-improved Professional Summary / About section.",
    )
    experience: Optional[List[AIProfileExperienceEntry]] = Field(
        default=None,
        description="AI-rewritten experience descriptions, one per existing resume experience entry, in the same order.",
    )

    model_config = ConfigDict(from_attributes=True)