from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


HIRING_RECOMMENDATIONS = (
    "Excellent Fit",
    "Good Fit",
    "Moderate Fit",
    "Low Fit",
)


class JobMatchScoreResponse(BaseModel):
    """AI Job Match Score API response.

    Generated by AWS Bedrock (see `app.service.ai_service.AIService`) from
    the logged-in candidate's profile + latest resume compared against a
    single job's full description. Unlike `SkillMatchResponse`
    (deterministic skill-set overlap only), this response is a richer,
    generative analysis covering experience fit, strengths/weaknesses, and
    a hiring recommendation.
    """

    job_id: str
    job_title: str

    match_score: float = Field(
        ge=0,
        le=100,
        description="AI-computed overall compatibility score between the candidate and this job (0-100).",
    )

    matching_skills: List[str] = Field(
        default_factory=list,
        description="Skills the candidate has that this job also calls for.",
    )
    missing_skills: List[str] = Field(
        default_factory=list,
        description="Skills this job calls for that the candidate's profile/resume does not show.",
    )

    experience_match_analysis: str = Field(
        default="",
        description="AI-generated analysis of how the candidate's experience aligns with this job's requirements.",
    )

    strengths: List[str] = Field(
        default_factory=list,
        description="Candidate strengths relevant to this job, per the AI analysis.",
    )
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Candidate gaps or weaknesses relevant to this job, per the AI analysis.",
    )

    hiring_recommendation: str = Field(
        description=f"One of: {', '.join(HIRING_RECOMMENDATIONS)}.",
    )

    improvement_suggestions: List[str] = Field(
        default_factory=list,
        description="Concrete, actionable suggestions for the candidate to improve their fit for this job.",
    )

    model_config = ConfigDict(from_attributes=True)